version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: handy-randy-app
    environment:
      - NODE_ENV=production
      - PORT=3010
      - DATABASE_PATH=/app/data/handy_randy.db
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - backend_data:/app/data
    ports:
      - "3010:3010"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3010/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_data:
    driver: local

networks:
  default:
    name: handy-randy-network