version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ndc-chatbot-backend-dev
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_PATH=/app/data/ndc_chatbot.db
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./backend:/app
      - backend_data:/app/data
      - /app/node_modules
    ports:
      - "3001:3001"
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ndc-chatbot-frontend-dev
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start

volumes:
  backend_data:
    driver: local